### ISSUE TITLE
ImportError: no module named 'xtend'

### ISSUE THREAD

**Issue by invincibleqc** [Hero-Wars-Dev-Team/Hero-Wars#7]
Seems like you forgot to add the xtend.py file. :wink:

**Comment by EinariTuukkanen** [comment]
You have to download 'xtend' separately. For further information, please have a look at quote from changelogs by Mahi below. 

"Xpand replaces commandlib
1. Hero-Wars is now dependant on Xpand, a custom package that "expands"
Source.Python's PlayerEntity. 
See http://github.com/MarkusMeskanen/Xpand for more information and the
download link."
